#!/bin/bash


trap 'kill -TERM $PID' TERM INT

export DAQDIR=/home/acqilc/SDHCAL
source ${DAQDIR}/bashrc
cd  ${DAQDIR}/levbdim_daq
export LD_LIBRARY_PATH=.:./lib:$LD_LIBRARY_PATH
./weblevbdim.py &

PID=$!
wait $PID
trap - TERM INT
wait $PID
EXIT_STATUS=$?
