#!/bin/bash


trap 'kill -TERM $PID' TERM INT

export DAQDIR=/home/acqilc/SDHCAL
source ${DAQDIR}/bashrc
cd  ${DAQDIR}/WtWizard/
export LD_LIBRARY_PATH=.:./lib:$LD_LIBRARY_PATH
./combined --docroot . --http-address `hostname -i` --http-port 9090 &

PID=$!
wait $PID
trap - TERM INT
wait $PID
EXIT_STATUS=$?
