DROP DATABASE GEOMETRY;
CREATE DATABASE GEOMETRY;
USE GEOMETRY;
CREATE TABLE VERSIONS (
IDX INTEGER PRIMARY KEY AUTO_INCREMENT,
TESTNAME VARCHAR(256) DEFAULT "NONE" ,
QUALITY INTEGER DEFAULT 0,
DEBUT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FIN TIMESTAMP DEFAULT 0,
VALID BOOLEAN DEFAULT 1
);

CREATE TABLE RUNS (
IDX INTEGER PRIMARY KEY AUTO_INCREMENT,
QUALITY INTEGER DEFAULT 0,
DEBUT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
RUN INTEGER DEFAULT 0,
VERSIONID INTEGER DEFAULT 0,
VALID BOOLEAN DEFAULT 1
);
CREATE TABLE FILES (
IDX INTEGER PRIMARY KEY AUTO_INCREMENT,
LOCATION VARCHAR(256) DEFAULT "NONE" ,
COMPRESS INTEGER DEFAULT 0,
RUN INTEGER DEFAULT 0,
VALID BOOLEAN DEFAULT 1
);
CREATE TABLE PLANS (
IDX INTEGER PRIMARY KEY AUTO_INCREMENT,
NUM INTEGER DEFAULT 0,
X0 REAL DEFAULT 0,
Y0 REAL DEFAULT 0,
Z0 REAL DEFAULT 0,
VERSIONID INTEGER DEFAULT 0,
VALID BOOLEAN DEFAULT 1
);
CREATE TABLE CHAMBERS (
IDX INTEGER PRIMARY KEY AUTO_INCREMENT,
NUM INTEGER DEFAULT 0,
X0 REAL DEFAULT 0,
Y0 REAL DEFAULT 0,
Z0 REAL DEFAULT 0,
X1 REAL DEFAULT 0,
Y1 REAL DEFAULT 0,
Z1 REAL DEFAULT 0,
PLANID INTEGER DEFAULT 0,
VERSIONID INTEGER DEFAULT 0,
VALID BOOLEAN DEFAULT 1
);
CREATE TABLE DIFS (
IDX INTEGER PRIMARY KEY AUTO_INCREMENT,
NUM INTEGER DEFAULT 0,
DI REAL DEFAULT 0,
DJ REAL DEFAULT 0,
POLI REAL DEFAULT 0,
POLJ REAL DEFAULT 0,
CHAMBERID INTEGER DEFAULT 0,
VERSIONID INTEGER DEFAULT 0,
VALID BOOLEAN DEFAULT 1
);

