DROP DATABASE SLOWFEB2016;
CREATE DATABASE SLOWFEB2016;
USE SLOWFEB2016;

CREATE TABLE CHAMBERREF (
IDX INTEGER PRIMARY KEY AUTO_INCREMENT,
CHAMBER INTEGER DEFAULT 0,
HVCHAN INTEGER DEFAULT 0,
VREF REAL DEFAULT 7200.0,
IREF REAL DEFAULT 500.0,
P0 REAL DEFAULT 1000.0,
T0 REAL DEFAULT 290.0,
DEBUT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
FIN  timestamp NOT NULL DEFAULT "2037-12-31 23:59:59"
);

CREATE TABLE WIENERMON (
IDX INTEGER PRIMARY KEY AUTO_INCREMENT,
HVCHAN INTEGER DEFAULT 0,
VSET REAL DEFAULT 0.0,
ISET REAL DEFAULT 0.0,
VOUT REAL DEFAULT 0.0,
IOUT REAL DEFAULT 0.0,
TIS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE BMPMON (
IDX INTEGER PRIMARY KEY AUTO_INCREMENT,
P REAL DEFAULT 0.0,
TK REAL DEFAULT 0.0,
TIS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

