import sys,os,commands
import  os
import re
import sys

def SWIGSharedLibrary(env, library, sources, **args):
  swigre = re.compile('(.*).i')
  if env.WhereIs('swig') is None:
    sourcesbis = []
    for source in sources:
      cName = swigre.sub(r'\1_wrap.c', source)
      cppName = swigre.sub(r'\1_wrap.cc', source)
      if os.path.exists(cName):
        sourcesbis.append(cName)
      elif os.path.exists(cppName):
        sourcesbis.append(cppName)
      else:
        sourcesbis.append(source)
  else:
    sourcesbis = sources
 
  if 'SWIGFLAGS' in args:
    args['SWIGFLAGS'] += ['-python']
  else:
    args['SWIGFLAGS'] = ['-python'] + env['SWIGFLAGS']
  args['SHLIBPREFIX']=""
  if sys.version >= '2.5':
    args['SHLIBSUFFIX']=".pyd"
 
  cat=env.SharedLibrary(library, sourcesbis, **args)
  return cat
 


# environment
#import xdaq
#print xdaq.INCLUDES
#print xdaq.LIBRARY_PATHS
#print xdaq.LIBRARIES

#print "----------------------------------------------"
Decider('MD5-timestamp')
XDAQ_ROOT="/opt/xdaq"
DHCAL_ROOT=os.path.abspath("..")


Bit64=False
Bit64=os.uname()[4]=='x86_64'
print Bit64

NetLink="../netLink"
if ( not os.path.exists(NetLink)):
 	NetLink=os.getenv("HOME")+"/netLink"
kl=os.uname()[2].split(".")
platform="UBUNTU"
if (kl[len(kl)-1][0:3] == 'el5'):
    platform="SLC5"

if (kl[len(kl)-2][0:3] == 'el6'):
    platform="SLC6"


fres=os.popen('uname -p')
kp=fres.readline()
osv=kp[0:len(kp)-1]

print platform,osv

Arm=os.uname()[4]=='armv7l'

if Arm:
  boostsystem='boost_system'
  boostthread='boost_thread'
else:
  boostsystem='boost_system-mt'
  boostthread='boost_thread-mt'

#includes
INCLUDES=['include',"/usr/include/boost141/",DHCAL_ROOT+"/SDHCAL_common/include",NetLink+"/include",NetLink+"/cslm","/usr/include/libftdi1"]


INCLUDES.append(commands.getoutput("python -c 'import distutils.sysconfig as conf; print conf.get_python_inc()'"))

CPPFLAGS=["-DLINUX", "-DREENTRANT" ,"-Dlinux", "-DLITTLE_ENDIAN__ ", "-Dx86",  "-DXERCES=2", "-DDAQ_VERSION_2"]

#Library ROOT + some of XDAQ + DB 


#LIBRARIES=['pthread', 'toolbox', 'xcept', 'config', 'log4cplus', 'asyncresolv', 'uuid', 'm', 'DHCDBUtils', 'occi', 'clntsh', 'nnz11', 'ilcconfdb', 'dbi', 'ftd2xx', 'stdc++','DHCEvent','ftdi','ftdipp']
if (platform == "UBUNTU"):
  LIBRARIES=['pthread',  'm', 'stdc++','ftdi','ftdipp','netlink','boost_system','boost_thread','log4cxx','cslm']
else:
  LIBRARIES=['pthread',  'm', 'stdc++','ftdi','ftdipp','netlink',boostsystem,boostthread,'cslm']


#Library path XDAQ,DHCAL and ROOT + Python
if (Bit64):
	LIBRARY_PATHS=["/usr/lib64","/usr/local/lib",NetLink+"/lib"]
else:
  LIBRARY_PATHS=["/usr/lib","/usr/local/lib",NetLink+"/lib"]
LIBRARY_PATHS.append(commands.getoutput("python -c 'import distutils.sysconfig as conf; print conf.PREFIX'")+"/lib")

#link flags
LDFLAGS=["-fPIC","-dynamiclib"]

# SWIG
SWIGSF=["-c++","-classic"]

for i in INCLUDES:
    SWIGSF.append("-I"+i)
print SWIGSF

# Create the Environment
env = Environment(CPPPATH=INCLUDES,CPPFLAGS=CPPFLAGS,LINKFLAGS=LDFLAGS, LIBS=LIBRARIES,LIBPATH=LIBRARY_PATHS,SWIGFLAGS=SWIGSF)

#print "CC is:",env.subst('$CPPPATH')

env['BUILDERS']['PythonModule'] = SWIGSharedLibrary


# Library source
LIBRARY_SOURCES=Glob("#src/*.cc")

#Shared library
SDHCALReadout=env.SharedLibrary("#lib/SDHCALReadout",LIBRARY_SOURCES)


#Daemon 
EXE_LIBPATH=LIBRARY_PATHS
EXE_LIBPATH.append("#lib")
EXE_LIBS=LIBRARIES
EXE_LIBS.append("SDHCALReadout")
dsv=env.Program("bin/dsv",source="src/dsv.cxx",LIBPATH=EXE_LIBPATH,LIBS=EXE_LIBS)
dsdcc=env.Program("bin/dsdcc",source="src/dsdcc.cxx",LIBPATH=EXE_LIBPATH,LIBS=EXE_LIBS)
mdcc=env.Program("bin/mdcc",source="src/testmdcc.cxx",LIBPATH=EXE_LIBPATH,LIBS=EXE_LIBS)


#Python module
_SDHCALReadout=env.PythonModule('_LSDHCALReadout', ['LSDHCALReadout.i'],LIBPATH="#lib",LIBS="SDHCALReadout")

myinc=[]
for x in Glob("#include/*.h"):
  myinc.append("include/"+x.name)
print myinc
env.Install(DHCAL_ROOT+"/opt/dhcal/lib",SDHCALReadout)
env.Install(DHCAL_ROOT+"/opt/dhcal/lib",SDHCALReadout)
env.Install(DHCAL_ROOT+"/opt/dhcal/bin",dsv)
env.Install(DHCAL_ROOT+"/opt/dhcal/bin",dsdcc)
env.Install(DHCAL_ROOT+"/opt/dhcal/bin",mdcc)
env.Install(DHCAL_ROOT+"/opt/dhcal/bin","#bin/ListDevices.py")
env.Install(DHCAL_ROOT+"/opt/dhcal/bin","#bin/scan_devices.sh")
env.Install(DHCAL_ROOT+"/opt/dhcal/include/readout",myinc)

env.Alias('install', [DHCAL_ROOT+"/opt/dhcal/lib",DHCAL_ROOT+"/opt/dhcal/bin"])



