InputFileDir="/data/online/Results/"
Instance=0
InputFilePattern="DHCAL_%d_I%d_%d.slcio"

Marlin="/data/DB/xml/autoGenerated_MARLIN.xml"
useSynchronized=True
OutputFilePattern="/tmp/Streamed_5inSynch_%d.slcio"
minChambersInTime=5
