#marlin="./Slot1_39_MARLIN.xml"
marlin="xml/can38.xml"
rebuild=True
useSynch=True
#
minChambersInTime=5;
filePath="/data/NAS/Results/DHCAL_%d_I%d_%d.slcio"
fileOut="/home/mirabito/DHCAL_%d_SO_O.slcio"
nevent=0
xdaqShift=92;
